before:
  hooks:
    - go mod tidy

builds:
  - id: uhr
    env:
      - CGO_ENABLED=0
    targets: [go_first_class]
    main: ./cmd/uhr/
  - id: wisuhr
    binary: wisuhr
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    main: ./cmd/wisuhr/

archives:
  - id: uhr
    builds: [uhr]
    name_template: "uhr_{{ .Os }}_{{ .Arch }}"
  - id: wisuhr
    builds: [wisuhr]
    name_template: "wisuhr_{{ .Os }}_{{ .Arch }}"

nfpms:
  - vendor: Becker Software LTDA
    homepage: https://carlosbecker.com
    maintainer: Carlos Becker <root@carlosbecker.dev>
    description: Zeichenorientierte Benutzerschnittstelle Uhr
    formats:
      - deb
      - apk
      - rpm

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features and updates"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
